import { test, expect } from './fixtures'

test('demonstração liga cliente, empresa e profissional, com reagendamento e cancelamento', async ({ page, api }) => {
  await page.clock.setFixedTime(new Date('2099-01-01T12:00:00Z'))
  await page.goto('/demo')
  await expect(page.getByText('Demonstração · dados fictícios', { exact: true })).toBeVisible()
  await page.getByRole('combobox', { name: 'Horário', exact: true }).selectOption({ index: 1 })
  await page.getByLabel('Nome fictício').fill('Visitante de exemplo')
  await page.getByRole('button', { name: 'Rever reserva', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar reserva de demonstração' }).click()
  const card = page.getByRole('article', { name: 'Reserva de Visitante de exemplo' })
  await expect(card).toBeVisible()
  await page.getByRole('button', { name: 'Empresa', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Reservas da empresa - Miguel' })).toBeVisible()
  await expect(card.getByText('Profissional', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Ana', exact: true }).click()
  await expect(card).toHaveCount(0)
  await page.getByRole('button', { name: 'Agenda do Miguel', exact: true }).click()
  await expect(card.getByText('Profissional', { exact: true })).toHaveCount(0)
  await card.getByRole('button', { name: 'Reagendar reserva' }).click()
  const dialog = page.getByRole('dialog', { name: 'Reagendar reserva' })
  await dialog.getByRole('combobox', { name: 'Data', exact: true }).selectOption({ index: 1 })
  await dialog.getByRole('combobox', { name: 'Horário', exact: true }).selectOption({ index: 1 })
  await dialog.getByRole('button', { name: 'Confirmar novo horário' }).click()
  await expect(card.getByText(/03\/01\/2099/)).toBeVisible()
  await page.getByRole('button', { name: 'Cliente', exact: true }).click()
  await expect(card.getByText(/03\/01\/2099/)).toBeVisible()
  await card.getByRole('button', { name: 'Cancelar reserva', exact: true }).click()
  await page.getByRole('button', { name: 'Confirmar cancelamento' }).click()
  await expect(card.getByText('Cancelada', { exact: true })).toBeVisible()
  await page.reload()
  await expect(card.getByText('Cancelada', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Repor exemplos' }).click()
  await page.getByRole('button', { name: 'Confirmar reposição' }).click()
  await expect(page.getByRole('heading', { name: 'Experimentar uma reserva' })).toBeVisible()
  await expect(card).toHaveCount(0)
  expect(api.calls).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('demonstração não inicia o cliente Supabase nem altera uma sessão existente', async ({ page, api }) => {
  await api.signIn('72000000-0000-4000-8000-000000000001')
  const loaded: string[] = []
  page.on('request', (request) => loaded.push(new URL(request.url()).pathname))
  await page.goto('/demo/')
  await expect(page.getByRole('heading', { name: 'Uma reserva, de ambos os lados.' })).toBeVisible()
  const before = await page.evaluate(() => localStorage.getItem('sb-booking-test-auth-token'))
  expect(before).not.toBeNull()
  await page.getByRole('button', { name: 'Repor exemplos' }).click()
  await page.getByRole('button', { name: 'Confirmar reposição' }).click()
  expect(await page.evaluate(() => localStorage.getItem('sb-booking-test-auth-token'))).toBe(before)
  expect(loaded.filter((path) => /\/assets\/(live-app|client)-/.test(path))).toEqual([])
  expect(api.calls).toEqual([])
})

test('dados de demonstração inválidos não impedem abrir a página', async ({ page, api }) => {
  await page.addInitScript(() => sessionStorage.setItem('booking-demo-v1', '{invalid'))
  await page.goto('/demo')
  await page.getByRole('button', { name: 'Empresa', exact: true }).click()
  await expect(page.getByRole('article', { name: 'Reserva de João (exemplo)' })).toBeVisible()
  expect(api.calls).toEqual([])
})

test('a página inicial oferece entrada e saída da demonstração', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Experimentar demonstração' }).click()
  await expect(page).toHaveURL(/\/demo$/)
  await expect(page).toHaveTitle('Demonstração · Booking SaaS')
  await page.getByRole('link', { name: 'Sair da demonstração' }).click()
  await expect(page).toHaveURL('http://127.0.0.1:4177/')
  await expect(page.getByRole('link', { name: 'Criar conta' })).toBeVisible()
})
